on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Create config file
      run: |
        pwd
        echo Access $AWS_ACCESS_KEY_ID
        env
        echo "apiSecret: $apiSecret" > config.dev.yml
        echo "domain: $domain" >> config.dev.yml
        ls -la
    - name: serverless install
      uses: serverless/github-action@v1.53.0
      with:
        args: plugin install --name serverless-api-gateway-throttling
    - name: serverless deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
